### ISSUE TITLE
`ns.codingcontract.attempt()` doesn't hide log when `ns.disableLog("ALL");` is used.

### ISSUE THREAD

**Issue by Domanoc** [danielyxie/bitburner#2576]
When running code like this:

```javascript
ns.disableLog("ALL");

const answer = "correct answer/incorrect answer";
const filename = "contract_filename";
const hostname = "hostname";

ns.codingcontract.attempt(anwser, filename, hostname, { returnReward: true });
```

The attempt will still print its default log message to the log. while the expected behavior would be that it is suppressed.

**Comment by deathly809** [comment]
When I try to run your example I get an error.  You have declared answer twice.  What output are you getting and where is it located?

**Comment by Domanoc** [comment]
fixed the typo in the example but here is a better one.

made the file ContractExample.js on the home server root
```javascript
/** @param {NS} ns **/
export async function main(ns) {
    ns.disableLog("ALL");

    const answer = "correct answer/incorrect answer";
    const filename = "contract-486229.cct"; //contract_filename;
    const hostname = "taiyang-digital"; //hostname

    ns.codingcontract.attempt(answer, filename, hostname, { returnReward: true });
}
```

In my case i happen to have a contract on "taiyang-digital" with filename "contract-486229.cct".

when running i get the following log
![afbeelding](https://user-images.githubusercontent.com/21247809/149094809-f9fc376f-2650-4d09-99c0-047648cd83be.png)

while i would expect to get a log with only the line for "script finished running"

**Comment by Domanoc** [comment]
Same result on a succesfull answer:

![afbeelding](https://user-images.githubusercontent.com/21247809/149128758-129c8126-7c57-47c1-9dff-b776fedc922b.png)

**Comment by iBreakEverything** [comment]
Can confirm. I call disableLog at the start of the function and it still get written to log. [File here](https://github.com/iBreakEverything/bitburner-tools/blob/master/iBreakEverything/daemon/ContractSolver.js)
![log](https://user-images.githubusercontent.com/1362764/149213020-45fff896-b47c-440f-8ee2-53198ca80509.png)

**Comment by deathly809** [comment]
We log claiming to be the function called attempt.  We did not include the prefix "ns.codingcontract.".  I will do a PR in a few.
```ts
        workerScript.log("attempt", () => `Successfully completed Coding Contract '${filename}'. Reward: ${reward}`);
```

**Comment by deathly809** [comment]
Actually, when we generate the list of all available functions we are not correctly adding the sub-module functions.  Will look into that.

**Comment by deathly809** [comment]
Welp, bad news.  This is not the only API with this problem, this is going to be a bunch of tedious work.  Could take me a day or so to find and update them all.

**Comment by deathly809** [comment]
@hydroflame  - Two options, thoughts?

1. Flatten the functions out of their namespaces.  Pros: Less Work, Cons: We cannot have two functions with same name, ever.
2. I go and add all the namespaces (but not the ns. prefix lol). Pros: The correct solution and allows function name reuse.  Cons: So many of these functions are wrong.

**Comment by deathly809** [comment]
Luckily this was a lot less work than I thought!  Only a handful of functions were not handling logging correctly.

**Comment by Domanoc** [comment]
Verified steam and web version (Bitburner v1.3.0 (9fdc3ac5)) have this now fixed.
